# Reduce binary size
[build]
rustflags = "-Z location-detail=none"

# Enable rust-lld linker where available
[target.'cfg(all(not(target_os = "android"), not(target_os = "linux")))']
linker = "rust-lld"
