# Enable rust-lld linker where available
[target.'cfg(not(target_os = "android"))']
linker = "rust-lld"

# Reduce binary size
[target.'cfg(not(target_os = "linux"))']
rustflags = "-Z location-detail=none"
